version: "3"

services:
   
    app:
     environment:
       - CM_EXAMPLE_PROJECTS=false
     #command: bash /upload_to_postgres.sh
  
    web:
      build: web
      ports:
        - "8001:80"
      volumes:
        - /FAFB_RAID:/data/external
        - ../temca2/temca2_v13:/etc/nginx/sites-available/temca2v_13
